Hospital(Mvc)/Models/Doctor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hospital_Mvc_.Models
{
    public class Doctor
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int DoctorId { get; set; }

        [MinLength(5)]
        [MaxLength(50)]
        public string DoctorName { get; set; }

        [Range(22, 50)]
        public int DoctorAge { get; set; }

        [MinLength(5)]
        [MaxLength(50)]
        public string Address { get; set; }

        public bool IsActive { get; set; }

    }
}

Hospital(Mvc)/Models/DoctorMediciVM.cs
namespace Hospital_Mvc_.Models
{
    public class DoctorMediciVM
    {
        public List<Doctor> DoctorsVM { get; set; }

        public List<Medicine> medicinesVM { get; set; }
    }
}

Hospital(Mvc)/Models/ErrorViewModel.cs
namespace Hospital_Mvc_.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hospital(Mvc)/Models/Medicine.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hospital_Mvc_.Models
{
    public class Medicine
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MedicineId { get; set; }

        [MinLength(5)]
        [MaxLength(50)]
        public string MedicineName { get; set; }

        
    }
}

Hospital(Mvc)/Models/Patient.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Hospital_Mvc_.Models
{
    public class Patient
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PatientId { get; set; }

        [MinLength(5)]
        [MaxLength(50)]
        public string PatientName { get; set; }


        public int PatientAge { get; set; }

        [MinLength(5)]
        [MaxLength(50)]
        public string City { get; set; }


        //here DoctorId forignkey
        public int DoctorId { get; set; }
        public Doctor Doctor { get; set; }


        //here Medicineid forignkey
        public int MedicineId { get; set; }
        public Medicine Medicine { get; set; }

        [Range(1, 5)]
        public int HowManyTimsDay { get; set; }
    }
}

Hospital(Mvc)/Controllers/DoctorController.cs
using Hospital_Mvc_.Models;
using Hospital_Mvc_.Repositry;
using Microsoft.AspNetCore.Mvc;

namespace Hospital_Mvc_.Controllers
{
    public class DoctorController : Controller
    {
        private readonly IDoctorRepositry _doctorRepositry;

        public DoctorController(IDoctorRepositry doctorRepositry)
        {
            _doctorRepositry = doctorRepositry; 
            
        }
        //list all doctors
        [HttpGet]
        public ActionResult Index()
        {
            List<Doctor> lista = _doctorRepositry.GetAllDoctor();
            return View(lista);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]

       
        public ActionResult Create(Doctor doctor)
        {
            _doctorRepositry.Create(doctor);
            List<Doctor> lista = _doctorRepositry.GetAllDoctor();
            return View("Index", lista);
        }

        public ViewResult Delete(int id)
        {
            _doctorRepositry.Delete(id);
            List<Doctor> lista = _doctorRepositry.GetAllDoctor();
            return View("Index",lista);
        }
    }
}

Hospital(Mvc)/Controllers/HomeController.cs
using Hospital_Mvc_.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Hospital_Mvc_.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hospital(Mvc)/Controllers/MedicineController.cs
using Hospital_Mvc_.Models;
using Hospital_Mvc_.Repositry;
using Microsoft.AspNetCore.Mvc;

namespace Hospital_Mvc_.Controllers
{
    public class MedicineController : Controller
    {
        private readonly IMedicineRepositry _medicineRepositry;

        public MedicineController(IMedicineRepositry medicineRepositry)
        {
            _medicineRepositry = medicineRepositry; 
            
        }
        //list all Medicine
        [HttpGet]
        public ActionResult Index()
        {
            List<Medicine> lista = _medicineRepositry.GetAllMedicine();
            return View(lista);
        }


        [HttpGet]
        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Create(Medicine medicine)
        {
            _medicineRepositry.Create(medicine);
            List<Medicine> lista = _medicineRepositry.GetAllMedicine();
            return View("Index",lista);
        }

        public ViewResult Delete(int id)
        {
            _medicineRepositry.Delete(id);
            List<Medicine> lista = _medicineRepositry.GetAllMedicine();
            return View("Index", lista);
        }
    }
}

Hospital(Mvc)/Controllers/PatientController.cs
using Hospital_Mvc_.Models;
using Hospital_Mvc_.Repositry;
using Microsoft.AspNetCore.Mvc;

namespace Hospital_Mvc_.Controllers
{
    public class PatientController : Controller
    {
        private readonly IPatientRepositry _patientRepositry;
        private readonly IMedicineRepositry _medicineRepositry; 
        private readonly IDoctorRepositry _odctorRepositry; 
        public PatientController(IPatientRepositry patientRepositry, IMedicineRepositry medicineRepositry, IDoctorRepositry odctorRepositry)
        {
            _patientRepositry = patientRepositry;
            _medicineRepositry = medicineRepositry;
            _odctorRepositry = odctorRepositry;
        }
        //list all Patient
        [HttpGet]
        public ActionResult Index()
        {
            List<Patient> listo = _patientRepositry.GetAllPatient();
            return View(listo);
        }


        [HttpGet]
        public ActionResult Create()
        {
            DoctorMediciVM doctorMediciVM = new DoctorMediciVM();
            doctorMediciVM.DoctorsVM = _odctorRepositry.GetAllDoctor();
            doctorMediciVM.medicinesVM=_medicineRepositry.GetAllMedicine();

            return View(doctorMediciVM);
        }

        [HttpPost]
     
        public ActionResult Create(Patient patient)
        {
            _patientRepositry.Create(patient);
            List<Patient> listo = _patientRepositry.GetAllPatient();
            return View("Index", listo);
        }


        public ViewResult Delete(int id)
        {
            _patientRepositry.Delete(id);
            List<Patient> listo = _patientRepositry.GetAllPatient();
            return View("Index",listo);
        }

    }
}

Hospital(Mvc)/Views/Doctor/Create.cshtml
@{
    Layout = null;
}


<style>
     #linko {
        color:black;
        font-size: 20px;
        text-decoration: none;
        border:2px solid black;
        padding:5px 20px;
       margin-top:20px;
       margin-left:20px;
        display:inline-block;
       border-radius:20px;
        transition: 1s;
       
      
    }

    #linko:hover{
        color:white;
        background-color:black;
       
        
    }
        </style>

<div class="row">
    <div class="col-2-md">
        <a id="linko" href="/Doctor/Index">Back To List</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <form action="Create" method="post">
          

            <fieldset>

                <legend><span class="number">1</span> Doctor Info</legend>

                <label for="name">Name:</label>
                <input type="text" id="name" name="DoctorName">

                <label for="text">Doctor Age</label>
                <input type="text" id="mail" name="DoctorAge">

                <label for="password">Address:</label>
                <input type="text" id="Address" name="Address">

                <label>Is Active</label>
                <input type="checkbox" id="avtivr" value="True" name="IsActive" checked>
              

            </fieldset>
         @*    <fieldset>

                <select id="job" name="user_job">
                    <optgroup label="Web">
                        <option value="frontend_developer">Front-End Developer</option>
                        <option value="php_developer">PHP Developer</option>
                        <option value="python_developer">Python Developer</option>
                        <option value="rails_developer">Rails Developer</option>
                        <option value="web_designer">Web Designer</option>
                        <option value="wordpress_developer">Wordpress Developer</option>
                    </optgroup>
                 
                
                </select>

             

            </fieldset> *@

            <button type="submit">Save</button>

        </form>
    </div>
</div>


                <style>
                    form {
  max-width: 400px;
  margin: 10px auto;
  padding: 10px 20px;
  background: #f4f7f8;
  border-radius: 8px;
  max-height:250px;
}

h1 {
  margin: 0 0 30px 0;
  text-align: center;
}

input[type="text"],
input[type="password"],
input[type="date"],
input[type="datetime"],
input[type="email"],
input[type="number"],
input[type="search"],
input[type="tel"],
input[type="time"],
input[type="url"],
textarea,
select {
  background: rgba(255,255,255,0.1);
  border: none;
  font-size: 16px;
  height: auto;
  margin: 0;
  outline: 0;
  padding: 15px;
  width: 100%;
  background-color: #e8eeef;
  color: #8a97a0;
  box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
  margin-bottom: 30px;
}

input[type="radio"],
input[type="checkbox"] {
  margin: 0 4px 8px 0;
}

select {
  padding: 6px;
  height: 32px;
  border-radius: 2px;
}

button {
  padding: 19px 39px 18px 39px;
  color: #FFF;
  background-color: #4bc970;
  font-size: 18px;
  text-align: center;
  font-style: normal;
  border-radius: 5px;
  width:200px;
  border: 1px solid #3ac162;
  border-width: 1px 1px 3px;
  box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
  margin-bottom: 10px;
}

fieldset {
  margin-bottom: 30px;
  border: none;
}

legend {
  font-size: 1.4em;
  margin-bottom: 10px;
}

label {
  display: block;
  margin-bottom: 8px;
}

label.light {
  font-weight: 300;
  display: inline;
}

.number {
  background-color: #5fcf80;
  color: #fff;
  height: 30px;
  width: 30px;
  display: inline-block;
  font-size: 0.8em;
  margin-right: 4px;
  line-height: 30px;
  text-align: center;
  text-shadow: 0 1px 0 rgba(255,255,255,0.2);
  border-radius: 100%;
}

media screen and (min-width: 480px) {

  form {
    max-width: 480px;
  }

}

                </style>

Hospital(Mvc)/Views/Doctor/Index.cshtml
@model List<Doctor>
<link href="~/css/table.css" rel="stylesheet" />



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    #button a{
        color:white;
        font-size:20px;
        text-decoration:none;
    }
</style>

<button id="button" type="button" class="btn btn-primary"><a  asp-area="" asp-controller="Doctor" asp-action="Create">create Doctor</a></button>
<div class="container">
    <div class="table-responsive">
        <table class="table table-bordered   table-striped" style="margin-top:0px">
            <thead class="table__head">
                <tr class="winner__table">
                   
                    <th><i class="fa fa-user-md" aria-hidden="true"></i> Doctor Name</th>
                    <th><i class="fa fa-child" aria-hidden="true"></i> Doctor Age</th>
                    <th><i class="fa fa-toggle-on" aria-hidden="true"></i> IS Active</th>
                    <th><i class="fa fa-map-marker" aria-hidden="true"></i> Address</th>
                    
                    <th><i class="fa fa-trash" aria-hidden="true"></i> Delete</th>
                    
                </tr>
            </thead>
          @foreach(Doctor I in Model)
            {
                <tbody>
                    <tr class="winner__table">
                        <td>@I.DoctorName</td>
                        <td>@I.DoctorAge</td>
                        <td>@I.IsActive</td>
                        <td>@I.Address</td>
                       
                       
                        <td><a href="/Doctor/Delete/@I.DoctorId"><i class="fa fa-trash-o" style="font-size:20px;color:#4F89D4"></i></a></td>
                        
                    </tr>



                </tbody>
            }
        </table>
    </div>
</div>

Hospital(Mvc)/Views/Medicine/Create.cshtml
@{
    Layout = null;
}


<style>
    #linko {
        color: black;
        font-size: 20px;
        text-decoration: none;
        border: 2px solid black;
        padding: 5px 20px;
        margin-top: 20px;
        margin-left: 20px;
        display: inline-block;
        border-radius: 20px;
        transition: 1s;
    }

        #linko:hover {
            color: white;
            background-color: black;
        }
</style>

<div class="row">
    <div class="col-2-md">
        <a id="linko" href="/Medicine/Index">Back To List</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <form action="Create" method="post">


            <fieldset>

                <legend><span class="number">1</span> Medicine Info</legend>

                <label for="name">Medicine Name</label>
                <input type="text" id="name" name="MedicineName">



            </fieldset>
            @*    <fieldset>

            <select id="job" name="user_job">
            <optgroup label="Web">
            <option value="frontend_developer">Front-End Developer</option>
            <option value="php_developer">PHP Developer</option>
            <option value="python_developer">Python Developer</option>
            <option value="rails_developer">Rails Developer</option>
            <option value="web_designer">Web Designer</option>
            <option value="wordpress_developer">Wordpress Developer</option>
            </optgroup>


            </select>



            </fieldset> *@

            <button type="submit">Save</button>

        </form>
    </div>
</div>


<style>
    form {
        max-width: 400px;
        margin: 10px auto;
        padding: 10px 20px;
        background: #f4f7f8;
        border-radius: 8px;
        max-height: 250px;
    }

    h1 {
        margin: 0 0 30px 0;
        text-align: center;
    }

    input[type="text"],
    input[type="password"],
    input[type="date"],
    input[type="datetime"],
    input[type="email"],
    input[type="number"],
    input[type="search"],
    input[type="tel"],
    input[type="time"],
    input[type="url"],
    textarea,
    select {
        background: rgba(255,255,255,0.1);
        border: none;
        font-size: 16px;
        height: auto;
        margin: 0;
        outline: 0;
        padding: 15px;
        width: 100%;
        background-color: #e8eeef;
        color: #8a97a0;
        box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
        margin-bottom: 30px;
    }

    input[type="radio"],
    input[type="checkbox"] {
        margin: 0 4px 8px 0;
    }

    select {
        padding: 6px;
        height: 32px;
        border-radius: 2px;
    }

    button {
        padding: 19px 39px 18px 39px;
        color: #FFF;
        background-color: #4bc970;
        font-size: 18px;
        text-align: center;
        font-style: normal;
        border-radius: 5px;
        width: 200px;
        border: 1px solid #3ac162;
        border-width: 1px 1px 3px;
        box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
        margin-bottom: 10px;
    }

    fieldset {
        margin-bottom: 30px;
        border: none;
    }

    legend {
        font-size: 1.4em;
        margin-bottom: 10px;
    }

    label {
        display: block;
        margin-bottom: 8px;
    }

        label.light {
            font-weight: 300;
            display: inline;
        }

    .number {
        background-color: #5fcf80;
        color: #fff;
        height: 30px;
        width: 30px;
        display: inline-block;
        font-size: 0.8em;
        margin-right: 4px;
        line-height: 30px;
        text-align: center;
        text-shadow: 0 1px 0 rgba(255,255,255,0.2);
        border-radius: 100%;
    }

    media screen and (min-width: 480px) {
        form

    {
        max-width: 480px;
    }

    }
</style>

Hospital(Mvc)/Views/Medicine/Index.cshtml
@model List<Medicine>

<link href="~/css/table.css" rel="stylesheet" />



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    #button a {
        color: white;
        font-size: 20px;
        text-decoration: none;
    }
</style>

<button id="button" type="button" class="btn btn-primary"><a asp-area="" asp-controller="Medicine" asp-action="Create">create Medicine</a></button>
<div class="container">
    <div class="table-responsive">
        <table class="table table-bordered   table-striped" >
            <thead class="table__head">
                <tr class="winner__table">

                    <th><i class="fa fa-cubes" aria-hidden="true"></i> Medicine Name</th>
                    
                    <th><i class="fa fa-trash" aria-hidden="true"></i> Delete</th>

                </tr>
            </thead>
            @foreach (Medicine I in Model)
            {
                <tbody>
                    <tr class="winner__table">
                        <td>@I.MedicineName</td>



                        <td><a href="/Medicine/Delete/@I.MedicineId"><i class="fa fa-trash-o" style="font-size:20px;color:#4F89D4"></i></a></td>

                    </tr>



                </tbody>
            }
        </table>
    </div>
</div>

Hospital(Mvc)/Views/Patient/Index.cshtml
@model List<Patient>

<link href="~/css/table.css" rel="stylesheet" />



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    #button a {
        color: white;
        font-size: 20px;
        text-decoration: none;
    }

  
</style>

<button id="button" type="button" class="btn btn-primary"><a asp-area="" asp-controller="Patient" asp-action="Create">create Patient</a></button>
<div class="container">
    <div class="table-responsive">
        <table class="table table-bordered   table-striped" >
            <thead class="table__head">
                <tr class="winner__table">

                    <th><i class="fa fa-user" aria-hidden="true"></i> Patient Name</th>
                    <th><i class="fa fa-child" aria-hidden="true"></i> Patient Age</th>
                    <th><i class="fa fa-map-marker" aria-hidden="true"></i> City</th>
                    <th><i class="fa fa-user-md" aria-hidden="true"></i> Doctor Name</th>
                    <th><i class="fa fa-pie-chart" aria-hidden="true"></i> Medicine Name</th> 
                    <th><i class="fa fa-pie-chart" aria-hidden="true"></i>How Many Tims Day</th>
                    <th><i class="fa fa-trash" aria-hidden="true"></i> Delete</th>

                </tr>
            </thead>
            @foreach (Patient I in Model)
            {
                <tbody>
                    <tr class="winner__table">
                        <td>@I.PatientName</td>
                        <td>@I.PatientAge</td>
                        <td>@I.City</td>
                        <td>@I.DoctorId</td>
                        <td>@I.MedicineId</td>
                        <td>@I.HowManyTimsDay</td>
                


                        <td><a href="/Patient/Delete/@I.PatientId"><i class="fa fa-trash-o" style="font-size:20px;color:#4F89D4"></i></a></td>

                    </tr>



                </tbody>
            }
        </table>
    </div>
</div>

Hospital(Mvc)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hospital_Mvc_</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hospital_Mvc_.styles.css" asp-append-version="true" />
    <script src="~/js/site.js"></script>
</head>
<body>
@*     <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hospital_Mvc_</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                  

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Doctor</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="Index">Patient</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Medicine" asp-action="Index">Medicine</a>
                        </li>

                        
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@

  @*   ////// *@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   
    <nav class="main-menu">
        <ul>
            <li>
                <a href="/home/index">
                    <i class="fa fa-hospital-o fa-2x"></i>
                    <span class="nav-text">
                        home
                    </span>
                </a>

            </li>
            <li class="has-subnav">
                <a href="/Doctor/Index">
                    <i class="fa fa-user-md fa-2x"></i>
                    <span class="nav-text">
                        Doctor
                    </span>
                </a>

            </li>
            <li class="has-subnav">
                <a href="/Medicine/Index">
                    <i class="fa fa-heartbeat fa-2x"></i>
                    <span class="nav-text">
                        Medicine
                    </span>
                </a>

            </li>
            <li class="has-subnav">
                <a href="/Patient/Index">
                    <i class="fa fa-user fa-2x"></i>
                    <span class="nav-text">
                        Patient
                    </span>
                </a>

            </li>
           
            
         
           
        </ul>

        <ul class="logout">
            <li>
                <a href="#">
                    <i class="fa fa-power-off fa-2x"></i>
                    <span class="nav-text">
                        Logout
                    </span>
                </a>
            </li>
        </ul>
    </nav>


  @*   ////// *@

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Hospital_Mvc_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>